[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aaas = "3SjXbrVTBAxCpLT9fdYuSaMJnpHa1fxx7ncBFvoQsnrE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build-devnet = "anchor build -- --no-default-features --features devnet"
build-mainnet = "anchor build -- --no-default-features --features mainnet"

# Devnet program id (will be auto-synced with target/deploy/aaas-keypair.json)
[programs.devnet]
aaas = "3SjXbrVTBAxCpLT9fdYuSaMJnpHa1fxx7ncBFvoQsnrE"

